var albumes = [
  {
    album: "A head full of dreams",
    autor: "Coldplay",
    cover: "./source/covers/1.jpg",
    url: "https://open.spotify.com/album/3cfAM8b8KqJRoIzt3zLKqw",
    feel: "Warm",
    many: "me",
    where: "1",
    long: "45",
    popularity: "5"
  },
  {
    album: "1000 forms of fear",
    autor: "Sia",
    cover: "./source/covers/2.jpg",
    url: "https://open.spotify.com/album/3xFSl9lIRaYXIYkIn3OIl9",
    feel: "Nostalgic",
    many: "me",
    where: "3",
    long: "60",
    popularity: "5"
  },
  {
    album: "Gorillaz",
    autor: "Gorillaz",
    cover: "./source/covers/3.jpg",
    url: "https://open.spotify.com/album/4tUxQkrduOE8sfgwJ5BI2F",
    feel: "Rock",
    many: "couple",
    where: "4",
    long: "60",
    popularity: "3"
  },
  {
    album: "Born To die",
    autor: "Lana del Rey",
    cover: "./source/covers/4.jpg",
    url: "https://open.spotify.com/album/5VoeRuTrGhTbKelUfwymwu",
    feel: "Nostalgic",
    many: "me",
    where: "2",
    long: "45",
    popularity: "4"
  },
  {
    album: "Discovery",
    autor: "Daft Punk",
    cover: "./source/covers/5.jpg",
    url: "https://open.spotify.com/album/2noRn2Aes5aoNVsU6iWThc",
    feel: "party",
    many: "Cares",
    where: "6",
    long: "50",
    popularity: "2"
  },
  {
    album: "Me Rehuso",
    autor: "danny ocean",
    cover: "./source/covers/6.jpg",
    url: "https://open.spotify.com/album/4RrvIEhnaHKpFxsjXc4D7d",
    feel: "happy",
    many: "couple",
    where: "6",
    long: "30",
    popularity: "5"
  },
  {
    album: "Is there Anybody Out There?",
    autor: "A Great Big World",
    cover: "./source/covers/7.jpg",
    url: "https://open.spotify.com/album/3kwbwO3wtwyNo7zCFzWkcW",
    feel: "warn",
    many: "cares",
    where: "1",
    long: "60",
    popularity: "3"
  },
  {
    album: "Minutes To Midnight live around the world",
    autor: "Linking Park",
    cover: "./source/covers/8.jpg",
    url: "https://open.spotify.com/album/2tlTBLz2w52rpGCLBGyGw6",
    feel: "rock",
    many: "me",
    where: "3",
    long: "45",
    popularity: "5"
  },
  {
    album: "Handwritten",
    autor: "Shawn Mendes",
    cover: "./source/covers/9.jpg",
    url: "https://open.spotify.com/album/5wKylB0Zwnxz046O7po25D",
    feel: "raice",
    many: "me",
    where: "2",
    long: "60",
    popularity: "5"
  },
  {
    album: "Metallica",
    autor: "Metallica",
    cover: "./source/covers/10.jpg",
    url: "https://open.spotify.com/album/3A4zAmE5c4dUAAqEJz6hCH",
    feel: "Rock",
    many: "me",
    where: "2",
    long: "30",
    popularity: "1"
  },
  {
    album: "Drones",
    autor: "Muse",
    cover: "./source/covers/11.jpg",
    url: "https://open.spotify.com/album/2wart5Qjnvx1fd7LPdQxgJ",
    feel: "concentrated",
    many: "cares",
    where: "3",
    long: "60",
    popularity: "4"
  },
  {
    album: "the 20/20 Experience",
    autor: "Justin Timberlake",
    cover: "./source/covers/12.jpg",
    url: "https://open.spotify.com/album/0O82niJ0NpcptYRxogeEZu",
    feel: "Rock",
    many: "party",
    where: "4",
    long: "60",
    popularity: "4"
  },
  {
    album: "Eterno Agosto",
    autor: "Alvaro Soler",
    cover: "./source/covers/13.jpg",
    url: "https://open.spotify.com/album/54ixUZwSjqeb8bXMoec9xJ",
    feel: "happy",
    many: "couple",
    where: "4",
    long: "50",
    popularity: "5"
  },
  {
    album: "<|°_°|>",
    autor: "caravan palace",
    cover: "./source/covers/14.jpg",
    url: "https://open.spotify.com/user/veromoreno/playlist/0OI2yxsj2tr9XAgsYZM7Ry",
    feel: "raise",
    many: "party",
    where: "5",
    long: "45",
    popularity: "2"
  },
  {
    album: "Faded",
    autor: "Alan Walker",
    cover: "./source/covers/15.jpg",
    url: "https://open.spotify.com/album/5HMjpBO0v78ayq5lreAyDd",
    feel: "warn",
    many: "couple",
    where: "1",
    long: "60",
    popularity: "4"
  },
  {
    album: "The Boy Who Cried Wolf",
    autor: "Passenger",
    cover: "./source/covers/16.jpg",
    url: "https://open.spotify.com/album/7InXwqAvEmGgr661Gfkexi",
    feel: "Rock",
    many: "cares",
    where: "1",
    long: "30",
    popularity: "3"
  },
  {
    album: "Appetite for destruction",
    autor: "Guns N'Roses",
    cover: "./source/covers/17.jpg",
    url: "https://open.spotify.com/album/3I9Z1nDCL4E0cP62flcbI5",
    feel: "Rock",
    many: "Cares",
    where: "4",
    long: "45",
    popularity: "4"
  },
  {
    album: "Stories",
    autor: "Avicii",
    cover: "./source/covers/18.jpg",
    url: "https://open.spotify.com/album/5ttIIMPWCp2bvwsdAPcEXC",
    feel: "concentrated",
    many: "me",
    where: "5",
    long: "50",
    popularity: "5"
  },
  {
    album: "Unorthodox Jukebox",
    autor: "Bruno Mars",
    cover: "./source/covers/19.jpg",
    url: "https://open.spotify.com/album/58ufpQsJ1DS5kq4hhzQDiI",
    feel: "happy",
    many: "couple",
    where: "3",
    long: "30",
    popularity: "4"
  },
  {
    album: "Collage",
    autor: "The Chainsmokers",
    cover: "./source/covers/20.jpg",
    url: "https://open.spotify.com/album/22rp3PnM3q2mtTI0OGCzpq",
    feel: "raise",
    many: "me",
    where: "6",
    long: "60",
    popularity: "4"
  },
  {
    album: "Mylo Xyloto",
    autor: "Coldplay",
    cover: "./source/covers/21.jpg",
    url: "https://open.spotify.com/album/2R7iJz5uaHjLEVnMkloO18",
    feel: "Nostalgic",
    many: "me",
    where: "4",
    long: "45",
    popularity: "5"
  },
  {
    album: "Nothing but the Best",
    autor: "Frank Sinatra",
    cover: "./source/covers/22.jpg",
    url: "https://open.spotify.com/album/54jgcQieeiqZEuA8fb5CsZ",
    feel: "Nostalgic",
    many: "me",
    where: "3",
    long: "30",
    popularity: "2"
  },
  {
    album: "Demon Days",
    autor: "Gorillaz",
    cover: "./source/covers/23.jpg",
    url: "https://open.spotify.com/album/0bUTHlWbkSQysoM3VsWldT",
    feel: "raise",
    many: "party",
    where: "4",
    long: "50",
    popularity: "3"
  },
  {
    album: "Greastest hits II",
    autor: "Queen",
    cover: "./source/covers/24.jpg",
    url: "https://open.spotify.com/album/1uG9cIT7IRuq9NqFvKFUsI",
    feel: "Nostalgic",
    many: "me",
    where: "",
    long: "60",
    popularity: "1"
  },
  {
    album: "Cloud Nine",
    autor: "Kygo",
    cover: "./source/covers/25.jpg",
    url: "https://open.spotify.com/album/0uMIzWh1uEpHEBell4rlF8",
    feel: "party",
    many: "cares",
    where: "",
    long: "30",
    popularity: "4"
  },
  {
    album: "The Resistance",
    autor: "Muse",
    cover: "./source/covers/26.jpg",
    url: "https://open.spotify.com/album/0eFHYz8NmK75zSplL5qlfM",
    feel: "rock",
    many: "couple",
    where: "",
    long: "30",
    popularity: "2"
  },
  {
    album: "No lo hagas",
    autor: "Sanalejo",
    cover: "./source/covers/27.jpg",
    url: "https://open.spotify.com/album/1AKNhvhITpApjr5u7q5is3",
    feel: "Warm",
    many: "couple",
    where: "",
    long: "60",
    popularity: "3"
  },
  {
    album: "El amor y sus efectos secundarios",
    autor: "Morat",
    cover: "./source/covers/28.jpg",
    url: "https://open.spotify.com/album/7Dgly4mhNl8SqWGVz13OXU",
    feel: "Warm",
    many: "Three",
    where: "",
    long: "45",
    popularity: "5"
  },
  {
    album: "In a tidal wave of mystery",
    autor: "Capital Cities",
    cover: "./source/covers/29.jpg",
    url: "https://open.spotify.com/album/2R7iJz5uaHjLEVnMkloO18",
    feel: "raise",
    many: "cares",
    where: "",
    long: "30",
    popularity: "4"
  },
  {
    album: "Iron",
    autor: "Woodkid",
    cover: "./source/covers/30.jpg",
    url: "https://open.spotify.com/album/2R7iJz5uaHjLEVnMkloO18",
    feel: "raise",
    many: "me",
    where: "",
    long: "50",
    popularity: "2"
  }
];
